import { SUPER_ADMIN_ROLE } from "./user-role.constants";

export const DEFAULT_PERMISSIONS = [
  "dashboard.view",
  "sales.view",
  "sales.create",
  "sales.update",
  "sales.delete",
  "sales.cancel",
  "sales.return",
  "manufacturing.view",
  "manufacturing.order.view",
  "manufacturing.order.create",
  "manufacturing.manage",
  "warehouse.view",
  "warehouse.manage",
  "purchases.view",
  "purchases.create",
  "purchases.update",
  "purchases.delete",
  "purchases.manage",
  "products.view",
  "products.create",
  "products.update",
  "products.delete",
  "products.manage",
  "categories.create",
  "customers.view",
  "customers.create",
  "customers.update",
  "customers.delete",
  "customers.manage",
  "agents.view",
  "agents.create",
  "agents.update",
  "agents.delete",
  "agents.manage",
  "suppliers.view",
  "suppliers.create",
  "suppliers.update",
  "suppliers.delete",
  "suppliers.manage",
  "finance.view",
  "finance.create",
  "finance.manage",
  "employees.view",
  "employees.create",
  "employees.update",
  "employees.delete",
  "employees.manage",
  "reports.view",
  "settings.view",
  "settings.manage",
];

export const ROLE_PERMISSION_MAP: Record<string, string[]> = {
  [SUPER_ADMIN_ROLE]: ["*"],
  OWNER: DEFAULT_PERMISSIONS,
  ADMIN: DEFAULT_PERMISSIONS,
  MANAGER: DEFAULT_PERMISSIONS.filter((permission) => permission !== "settings.manage"),
  CASHIER: ["dashboard.view", "sales.view", "sales.create", "products.view", "customers.view", "customers.create"],
  WAREHOUSE: ["dashboard.view", "warehouse.view", "warehouse.manage", "products.view", "purchases.view"],
  SALES: ["dashboard.view", "sales.view", "sales.create", "customers.view", "customers.create", "agents.view", "agents.create", "products.view"],
  EMPLOYEE: ["dashboard.view"],
};
